openapi: 3.0.0
info:
  title: Catalog Service API
  version: "1.0"
  description: API documentation for the catalog service, handling categories and products.

paths:
  /categories:
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryRequest'
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'

  /categories/{id}:
    get:
      summary: Get a category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The category ID
      responses:
        '200':
          description: Category retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
        '404':
          description: Category not found

components:
  schemas:
    CategoryRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        restaurant_id:
          type: string
        country_code:
          type: string
          maxLength: 2

    CategoryResponse:
      type: object
      properties:
        category_id:
          type: string
        name:
          type: string
        description:
          type: string
        restaurant_id:
          type: string
        country_code:
          type: string
          maxLength: 2
